// IMMEDIATELY INVOKED FUNCTION EXPRESSIONS  

// WHEN WE HAVE A SITUATION LIKE

// WE HAVE TO CONNECT TO DATABASE IMMEDIATELY . FUNCTION MUST RUN IMMEDIATELY
// WE HAVE WRITE A CONNECTION
// THE CONNECTION CODE MUST BE NOT POLUTATED BY THE GLOBAL SCOPE..


(function chai(){  // named iife
    console.log("DATABASE IS CONNECTED");
})() ; // SEMICOLON HERE IS VERY IMPORTANT, WHERE TO STOP BECAUSE THE FLOW OF FUNCTION NEEDS TO TERMINATED..

(  (NAME) => { 
    console.log(`DATABASE IS CONNECTED MR, ${NAME}`);
})('SAKET')  ;        

(  () => { 
    console.log(`DATABASE IS CONNECTED MR, ${NAME}`);
})()  ;     //simple iife 