// IMMEDIATELY INVOKED FUNCTION EXPRESSIONS  

// WHEN WE HAVE A SITUATION LIKE

// WE HAVE TO CONNECT TO DATABASE IMMEDIATELY .
// WE HAVE WRITE A CONNECTION
// THE CONNECTION CODE MUST BE NOT POLUTATED BY THE GLOBAL SCOPE..


(function chai(){
    console.log("DATABASE IS CONNECTED");
})() ; // SEMICOLON HERE IS VERY IMPORTANT

(  (NAME) => {
    console.log(`DATABASE IS CONNECTED MR, ${NAME}`);
})('SAKET')     